require(tidyverse)
require(bio3d)

# script to read in .tem files generated by the JOY server and output table with all amino acid environment
# info for every position in a protein

#set wd to location with the relevant PDB file
setwd("/Users/user/OneDrive - The University of Manchester/SARS-CoV-2/Structure")

# build list of residue numbers from relevant PDB
# read pdb file
raw_pdb <- read.pdb("6vxx.PDB")

pdb_frame <- raw_pdb$atom
rm(raw_pdb)

pdb_frame <- as_tibble(pdb_frame)

# filter for Calpha atoms only
pdb_frame <- pdb_frame %>% 
  filter(elety == "CA")

# set working directory to location of tem and str file
setwd("./Crescendo/6vxx")
# read TEM file
raw_TEM <- read_file("6vxx.tem.txt")

split_element <- str_extract(raw_TEM,"((?<=^\\>).*(?=\\n))")

list_TEM <- str_split(raw_TEM, pattern=split_element,simplify=T)

list_TEM <- list_TEM[-1]

list_TEM <- as.list(list_TEM)

# # single element for function testing
 # TEM_element <- list_TEM[2]

# set up tibble with pdb information to bind to
TEM_master_output <- tibble(Resno = pdb_frame$resno, Chain = pdb_frame$chain)

process_TEM <- function(TEM_element){
  
  temp_name <- str_extract(TEM_element,"((?<=^\\n).*(?=\\n))")
  temp_name <- str_replace_all(temp_name,"\\s","_")
  
  temp_element <- str_replace(TEM_element,"(^\\n.*\\n)","")
  temp_element <- str_replace_all(temp_element,"(\\n)","")
  temp_element <- str_replace_all(temp_element,"(\\*)","")
  temp_element <- str_replace_all(temp_element,"(\\-)","")
  temp_element <- str_replace_all(temp_element,"(\\>)","")

  temp_element <- str_split_fixed(temp_element, pattern="",n=nchar(temp_element))
  
  temp_element <- as_tibble(temp_element)
  temp_element <- pivot_longer(temp_element, cols = everything(), names_to = NULL, values_to = temp_name)
  
  TEM_master_output <<- cbind(TEM_master_output, temp_element)
}

lapply(list_TEM,process_TEM)

TEM_master_output$sequence <- aa123(TEM_master_output$sequence)

write_csv(TEM_master_output, "6vxx_TEM_output.csv")
